name: Deploy Lambda - Suscriptor a tópico SNS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/guillevalin/devops-challenge.git
          cd devops-challenge

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and push Docker image
        env:
          DOCKER_REPO: guillevalin/app-suscriptor
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          LAMBDA_IMAGE_TAG: "latest"
        run: |
          cd app-suscriptor
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_REPO:$LAMBDA_IMAGE_TAG .
          docker push $DOCKER_REPO:$LAMBDA_IMAGE_TAG

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy to AWS Lambda
        env:
          LAMBDA_FUNCTION_NAME: "app-suscriptor"
          LAMBDA_ROLE: ${{ secrets.LAMBDA_ROLE }}
          DOCKER_REPO_URI: "guillevalin/app-suscriptor:latest"
        run: |
          aws lambda create-function \
            --function-name $LAMBDA_FUNCTION_NAME \
            --package-type Image \
            --code ImageUri=$DOCKER_REPO_URI \
            --role $LAMBDA_ROLE \
            --region us-east-1 \
          || aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri $DOCKER_REPO_URI \
            --region us-east-1