name: Deploy Lambda Docker Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}  # Define el repositorio de ECR en los secretos de GitHub
          AWS_REGION: us-east-1
          LAMBDA_IMAGE_TAG: "latest"
        run: |
          docker build -t $ECR_REPOSITORY:$LAMBDA_IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$LAMBDA_IMAGE_TAG $ECR_REPOSITORY:$LAMBDA_IMAGE_TAG
          docker push $ECR_REPOSITORY:$LAMBDA_IMAGE_TAG

      - name: Deploy to AWS Lambda
        env:
          LAMBDA_FUNCTION_NAME: "docker_lambda_function"  # Nombre de tu función Lambda
          ECR_REPOSITORY_URI: "${{ secrets.AWS_ECR_REPOSITORY }}:${{ LAMBDA_IMAGE_TAG }}"
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri $ECR_REPOSITORY_URI